### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Amerlander** [microsoft/pxt-calliope#214]
There are some parts of MakeCode that are not translated to german:

- [ ] "remainder of %1 / %2" is not translated. Should be "Rest von %1 ÷ %2"
- [ ] "serial write buffer" is not translated. Should be "seriell|schreibe Zwischenspeicher %buffer"
- [ ] Share Popup: Info-Box and Button

![image](https://user-images.githubusercontent.com/3764089/212646259-e18b97a8-1e53-4f97-b0c1-1acd50ca3495.png)
![image](https://user-images.githubusercontent.com/3764089/212646328-a2a88213-03a2-41a1-8737-d222a6f9f78f.png)

**Comment by joernalraun** [comment]
One thing to add: this items can‘t be translated through Crowdin, though they are there (and translated), but don‘t show up on MakeCode.

**Comment by joernalraun** [comment]
Are there any news on this – where should it be posted instead? This is a problem throughout all MakeCode platforms.

**Comment by MKleinSB** [comment]
![grafik](https://user-images.githubusercontent.com/37311672/219445969-863b4c1e-9d5e-48af-a511-861e40c9832d.png)

Serial write buffer is fixed now. 

described in
https://github.com/microsoft/pxt-microbit/issues/4873


![grafik](https://user-images.githubusercontent.com/37311672/219446889-bc30c6a0-b5ae-4e25-8481-a457b8d1bca7.png)
 
remainder has no String in Crowdin. I can´t fix it in  In-Context translation. The string disappeared around a year.

**Comment by joernalraun** [comment]
I still see Serial write buffer, but maybe it has just been fixed and it is still cached somewhere.
Remainder is also still not translated. The string seems to be available in Crowdin, but also other languages have this problem with it.

**Comment by MKleinSB** [comment]
Yes, it takes a day or so. 
makecode.calliope.cc/?translate=1#editor

**Comment by MKleinSB** [comment]
https://github.com/microsoft/pxt-microbit/issues/4904
 I think Galen Nickel is the right one but don´t want to post it twice

**Comment by MKleinSB** [comment]
Hm, after week the translated and approved text still does not appear in makecode. It appears only in in-context-translation
![grafik](https://user-images.githubusercontent.com/37311672/221019978-c78a0020-017d-4910-bd9b-d547c186d140.png)

**Comment by MKleinSB** [comment]
Now serial writebuffer now really ist fixed! 
remainder still remains :-(
